
name: UI Tests

on:
  push:
    branches: [ dev ]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
