
name: UI Tests

on:
  push:
    branches: [ dev ]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
