
name: UI Tests

on:
  push:
    branches: [ dev ]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # Execute UI tests
      - name: run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
